### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit__imaging)

### ISSUE THREAD

**Issue by mpeguese** [kivy/kivy-ios#644]
**Error: ImportError: dynamic module does not define module export function (PyInit__imaging)**

* Python : 3.9
* MacOS version : Big Sur
* XCode Version : 13.0
* Cython version : 0.29.24

ISSUE/BACKGROUND:
I am fairly new to python and attempting to create my first mobile app using KivyMD for iOS.  I am able to get the application onto my iPhone but it crashes with the below error.  It also fails on a Simulator as well with the exact same error.  I have followed all the steps outlined in kivy-ios ReadMe.  For reference I have placed my terminal commands below.

I found this same error in the [following post](https://github.com/kivymd/KivyMD/issues/1051) but it wasn't clearly answered as to what causes this error.  I also read several StackOverFlow posts and it appears to be a python2 vs python3 related error (Init being updated to PyInit with deprecation of PIL....or I could be wrong.  Please correct me as I am still new to all this) but I am using a virtual environment and made sure only python 3 is installed.  Can someone please help in advising what is causing this issue and how to go about fixing it?

ERROR:
Error: ImportError: dynamic module does not define module export function (PyInit__imaging)

TERMINAL COMMANDS:
brew install autoconf automake libtool pkg-config
brew link libtool
cd into local app directory ()
git clone https://github.com/kivy/kivy-ios.git
cd kivy-ios/
python3 -m venv venv
. venv/bin/activate
pip install -e .
pip install cython
python3 toolchain.py build kivy python3
python3 toolchain.py create <my project name> <local project directory>
open projectname.xcodeproj

**Xcode Build Logs**
2021-09-26 18:52:40.097319-0400 bebo[77985:4400838] Available orientation: KIVY_ORIENTATION=LandscapeLeft LandscapeRight Portrait PortraitUpsideDown
2021-09-26 18:52:40.097557-0400 bebo[77985:4400838] Initializing python
2021-09-26 18:52:40.530238-0400 bebo[77985:4400838] Running main.py: /Users/MikesMac/Library/Developer/CoreSimulator/Devices/91883F97-902C-41D8-BCA5-6F7CA24EEB27/data/Containers/Bundle/Application/90CB0A60-2777-4F62-A8DA-BB6E3A402CCB/bebo.app/YourApp/main.pyc
[INFO   ] [Kivy        ] v2.1.0.dev0
[INFO   ] [Kivy        ] Installed at "/Users/MikesMac/Library/Developer/CoreSimulator/Devices/91883F97-902C-41D8-BCA5-6F7CA24EEB27/data/Containers/Bundle/Application/90CB0A60-2777-4F62-A8DA-BB6E3A402CCB/bebo.app/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.9.2 (default, Sep 24 2021, 20:14:03) 
[Clang 13.0.0 (clang-1300.0.29.3)]
[INFO   ] [Python      ] Interpreter at "/Users/MikesMac/Library/Developer/CoreSimulator/Devices/91883F97-902C-41D8-BCA5-6F7CA24EEB27/data/Containers/Bundle/Application/90CB0A60-2777-4F62-A8DA-BB6E3A402CCB/bebo.app/bebo"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_imageio, img_tex (img_dds, img_sdl2, img_ffpyplayer, img_pil ignored)
[INFO   ] [KivyMD      ] 1.0.0.dev0 (installed at "/Users/MikesMac/Library/Developer/CoreSimulator/Devices/91883F97-902C-41D8-BCA5-6F7CA24EEB27/data/Containers/Bundle/Application/90CB0A60-2777-4F62-A8DA-BB6E3A402CCB/bebo.app/lib/python3.9/site-packages/kivymd/__init__.py")
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
2021-09-26 18:52:43.620702-0400 bebo[77985:4400838] Writing analzed variants.
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'OpenGL ES 2.0 APPLE-19.0.17'>
[INFO   ] [GL          ] OpenGL vendor <b'Apple Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Apple Software Renderer'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <b'OpenGL ES GLSL ES 1.00'>
[INFO   ] [GL          ] Texture max size <4096>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
Got dlopen error on Foundation: dlopen(/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 0x0001): tried: '/Users/MikesMac/Library/Developer/Xcode/DerivedData/bebo-divxpnhkpatmipasgnulhumpylxy/Build/Products/Debug-iphonesimulator/Foundation.framework/Versions/Current/Foundation' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file), '/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file), '/Users/MikesMac/Library/Developer/Xcode/DerivedData/bebo-divxpnhkpatmipasgnulhumpylxy/Build/Products/Debug-iphonesimulator/Foundation.framework/Versions/C/Foundation' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation' (no such file), '/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation' (no such file)
Got fallback dlopen error on Foundation: dlopen(/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 0x0001): tried: '/Users/MikesMac/Library/Developer/Xcode/DerivedData/bebo-divxpnhkpatmipasgnulhumpylxy/Build/Products/Debug-iphonesimulator/Foundation.framework/Versions/Current/Foundation' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file), '/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file), '/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation' (no such file)
 Traceback (most recent call last):
   File "<string>", line 44, in load_module
   File "/Users/MikesMac/ios-test/kivy-ios/dist/root/python3/lib/python3.9/imp.py", line 342, in load_dynamic
   File "<frozen importlib._bootstrap>", line 711, in _load
   File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
   File "<frozen importlib._bootstrap>", line 565, in module_from_spec
   File "<frozen importlib._bootstrap_external>", line 1108, in create_module
   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
 ImportError: dynamic module does not define module export function (PyInit_PIL__imaging)
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/Users/MikesMac/ios-test/kivy-ios/bebo-ios/YourApp/main.py", line 10, in <module>
   File "/Users/MikesMac/Library/Developer/CoreSimulator/Devices/91883F97-902C-41D8-BCA5-6F7CA24EEB27/data/Containers/Bundle/Application/90CB0A60-2777-4F62-A8DA-BB6E3A402CCB/bebo.app/lib/python3.9/site-packages/kivymd/uix/__init__.py", line 8, in <module>
     from kivymd.uix.behaviors import SpecificBackgroundColorBehavior
   File "/Users/MikesMac/Library/Developer/CoreSimulator/Devices/91883F97-902C-41D8-BCA5-6F7CA24EEB27/data/Containers/Bundle/Application/90CB0A60-2777-4F62-A8DA-BB6E3A402CCB/bebo.app/lib/python3.9/site-packages/kivymd/uix/behaviors/__init__.py", line 10, in <module>
     from .backgroundcolor_behavior import (
   File "/Users/MikesMac/Library/Developer/CoreSimulator/Devices/91883F97-902C-41D8-BCA5-6F7CA24EEB27/data/Containers/Bundle/Application/90CB0A60-2777-4F62-A8DA-BB6E3A402CCB/bebo.app/lib/python3.9/site-packages/kivymd/uix/behaviors/backgroundcolor_behavior.py", line 25, in <module>
     from .elevation import CommonElevationBehavior
   File "/Users/MikesMac/Library/Developer/CoreSimulator/Devices/91883F97-902C-41D8-BCA5-6F7CA24EEB27/data/Containers/Bundle/Application/90CB0A60-2777-4F62-A8DA-BB6E3A402CCB/bebo.app/lib/python3.9/site-packages/kivymd/uix/behaviors/elevation.py", line 364, in <module>
     from PIL import Image, ImageDraw, ImageFilter
   File "/Users/MikesMac/Library/Developer/CoreSimulator/Devices/91883F97-902C-41D8-BCA5-6F7CA24EEB27/data/Containers/Bundle/Application/90CB0A60-2777-4F62-A8DA-BB6E3A402CCB/bebo.app/lib/python3.9/site-packages/PIL/Image.py", line 114, in <module>
     from . import _imaging as core
   File "<string>", line 48, in load_module
   File "/Users/MikesMac/ios-test/kivy-ios/dist/root/python3/lib/python3.9/imp.py", line 342, in load_dynamic
 ImportError: dynamic module does not define module export function (PyInit__imaging)
2021-09-26 18:52:44.733397-0400 bebo[77985:4400838] Application quit abnormally!
2021-09-26 18:52:44.797039-0400 bebo[77985:4400838] Leaving

**Screenshots**
<img width="755" alt="screenshot_14" src="https://user-images.githubusercontent.com/91438833/134827534-ee1fe9ff-447e-4317-a060-90f267e13a36.png">

**Additional context**

**Comment by faris4017** [comment]
i have same error

**Comment by Jesscarlett** [comment]
Same error I had. The same code can be published to Google play without problem. In Xcode I had this PyInit_imaging erorr. Can't make it work, help please!

**Comment by Jesscarlett** [comment]
Hi all, me again. I managed to overcome the issue. I posted it to stackoverflow.
[https://stackoverflow.com/questions/69824628/kivymd-xcode-build-error-importerror-dynamic-module-does-not-define-module-ex/70080251#70080251](url)

**Comment by misl6** [comment]
@Jesscarlett this is due to #606.
The `kivy-ios` version available on PyPI is **1.2.1**, which doesn't include that patch, unlike the current `master` version which includes it.

I'm closing this issue, cause should be fixed via #606. But feel free to reopen if needed.

**Comment by K1NGC0D3R** [comment]
This is not working for me. Same error, no solution worked for me.

**Comment by jjosecarmona** [comment]
Please reopen the issue, cause it's not fixed.  My recipes show "pillow 8.2.0" but the error remains:

[INFO    ] Using the bundled version for recipe 'audiostream'
audiostream  master  
[INFO    ] Using the bundled version for recipe 'click'
click        7.1.2   
[INFO    ] Using the bundled version for recipe 'curly'
curly        master  
[INFO    ] Using the bundled version for recipe 'cymunk'
cymunk       master  
[INFO    ] Using the bundled version for recipe 'ffmpeg'
ffmpeg       n4.3.1  
[INFO    ] Using the bundled version for recipe 'ffpyplayer'
ffpyplayer   4.2.0   
[INFO    ] Using the bundled version for recipe 'flask'
flask        1.1.2   
[INFO    ] Using the bundled version for recipe 'freetype'
freetype     2.5.5   
[INFO    ] Using the bundled version for recipe 'host_setuptools'
[INFO    ] Using the bundled version for recipe 'host_setuptools3'
host_setuptools3 59.2.0  
[INFO    ] Using the bundled version for recipe 'hostopenssl'
hostopenssl  1.1.1l  
[INFO    ] Using the bundled version for recipe 'hostpython3'
hostpython3  3.9.9   
[INFO    ] Using the bundled version for recipe 'ios'
ios          master  
[INFO    ] Using the bundled version for recipe 'itsdangerous'
itsdangerous 1.1.0   
[INFO    ] Using the bundled version for recipe 'jinja2'
jinja2       2.11.2  
[INFO    ] Using the bundled version for recipe 'kivent_core'
kivent_core  master  
[INFO    ] Using the bundled version for recipe 'kivy'
kivy         b5ec51ed2315a9a890f264b0df6d23c8e6341d42
[INFO    ] Using the bundled version for recipe 'libcurl'
libcurl      7.65.3  
[INFO    ] Using the bundled version for recipe 'libffi'
libffi       3.2.1   
[INFO    ] Using the bundled version for recipe 'libjpeg'
libjpeg      v9d     
[INFO    ] Using the bundled version for recipe 'libpng'
libpng       1.6.26  
[INFO    ] Using the bundled version for recipe 'libzbar'
libzbar      0.10    
[INFO    ] Using the bundled version for recipe 'markupsafe'
markupsafe   1.1.1   
[INFO    ] Using the bundled version for recipe 'netifaces'
netifaces    0.10.9  
[INFO    ] Using the bundled version for recipe 'numpy'
numpy        1.20.2  
[INFO    ] Using the bundled version for recipe 'openssl'
openssl      1.1.1l  
[INFO    ] Using the bundled version for recipe 'photolibrary'
photolibrary master  
[INFO    ] Using the bundled version for recipe 'pillow'
pillow       8.2.0   
[INFO    ] Using the bundled version for recipe 'plyer'
plyer        master  
[INFO    ] Using the bundled version for recipe 'pycrypto'
pycrypto     2.6.1   
[INFO    ] Using the bundled version for recipe 'pykka'
pykka        1.2.1   
[INFO    ] Using the bundled version for recipe 'pyobjus'
pyobjus      master  
[INFO    ] Using the bundled version for recipe 'python3'
python3      3.9.9   
[INFO    ] Using the bundled version for recipe 'pyyaml'
pyyaml       3.11    
[INFO    ] Using the bundled version for recipe 'sdl2'
sdl2         7cc4fc886d9e
[INFO    ] Using the bundled version for recipe 'sdl2_image'
sdl2_image   2.0.4   
[INFO    ] Using the bundled version for recipe 'sdl2_mixer'
sdl2_mixer   2.0.4   
[INFO    ] Using the bundled version for recipe 'sdl2_ttf'
sdl2_ttf     2.0.15  
[INFO    ] Using the bundled version for recipe 'werkzeug'
werkzeug     1.0.1   
[INFO    ] Using the bundled version for recipe 'zbarlight'
zbarlight    1.2

**Comment by misl6** [comment]
HI @jjosecarmona and @K1NGC0D3R ,

I probably already suggested this fix to @K1NGC0D3R on Discord, but I'm not sure about the result.

Has Pillow been built after the code project creation?

If yes, did you updated the project accordingly via `toolchain update PATH/TO/YOUR.xcodeproj` ?

If `toolchain update ...` doesn't works, what happens if you manually add `libpillow.a` to your `General->Frameworks, Libraries, and Embedded Content` Xcode tab?

**Comment by K1NGC0D3R** [comment]
When I manually added libpillow.a

Xcode is now crashing after compiling

**Comment by K1NGC0D3R** [comment]
I fixed the crashing

But now new error

ImportError: The _imaging extension was built for another version of Pillow or PIL:
 Core version: 8.2.0
 Pillow version: 8.4.0
2021-12-10 11:27:05.355568+0530 bmicalc[8063:321372] Application quit abnormally!
2021-12-10 11:27:05.402427+0530 bmicalc[8063:321372] Leaving

**Comment by K1NGC0D3R** [comment]
I have fixed my error

Thank you

**Comment by misl6** [comment]
After some investigation on Discord, with a user that had the same issue, we came to a conclusion:

If `Pillow` (and could happen with other dependencies that actually need a recipe to build) is not built via `toolchain build pillow` **before** a dependant (Like `kivymd`) is installed via `toolchain pip install ....`, a non-recipe version of the dependency gets incorrectly installed.

That could lead to the issue that has been reported here.

As a workaround, until it get fixed, the following approach should be followed (I'm using as an example the specific `kivymd` case, but applies to others):
- `toolchain build python3 kivy`
- `toolchain build pillow`
- `toolchain pip install kivymd`

**Comment by lapp0** [comment]
I don't use this project, but I searched everywhere and this is one of the most active issues for this exact issue, so I thought I'd comment.

I resolved this error by using python3.9

**Comment by saminapoleon** [comment]
@misl6 
I had the same issue any fixing?

Regards,

**Comment by saminapoleon** [comment]
good morning all 

      I have the same issue and I tried all the solution above with no hop can any one provide me the right steps to over come this issue?

MacOs:big sur   running on VM

Issue:

 ImportError: dynamic module does not define module export function (PyInit__imaging)
2022-02-04 22:06:38.477149-0800 ios-app[26728:720920] Application quit abnormally!

hope to hear from you soon
 thanks in advance...

**Comment by misl6** [comment]
> After some investigation on Discord, with a user that had the same issue, we came to a conclusion:
> 
> If `Pillow` (and could happen with other dependencies that actually need a recipe to build) is not built via `toolchain build pillow` **before** a dependant (Like `kivymd`) is installed via `toolchain pip install ....`, a non-recipe version of the dependency gets incorrectly installed.
> 
> That could lead to the issue that has been reported here.
> 
> As a workaround, until it get fixed, the following approach should be followed (I'm using as an example the specific `kivymd` case, but applies to others):
> 
> * `toolchain build python3 kivy`
> * `toolchain build pillow`
> * `toolchain pip install kivymd`

@saminapoleon Did you tried to follow these instructions? (From a clean dist)

**Comment by saminapoleon** [comment]
@misl6 
hi and many thanx for your response,
what did you mean (From a clean dist)?
also I tried these 

    toolchain build python3 kivy
    toolchain build pillow
    toolchain pip install kivymd
but with no hope.

anything else must done?

Regards,

**Comment by saminapoleon** [comment]
@misl6 
I followed the instructions and
now I have this issue any idea?

 AttributeError: module 'subprocess' has no attribute 'Popen'

Regards

**Comment by misl6** [comment]
Are you using "subprocess" in your App?
If "yes", see: https://github.com/kivy/kivy-ios#why-does-the-python-multiprocesssubprocess-module-not-work

If you need some help or support, please join our [Discord Server](https://chat.kivy.org/)

**Comment by saminapoleon** [comment]
@misl6 

no im not using subprocess that is why im hanged out.

about discord I can not send any message I have no permission 

Regards,

**Comment by CryptoTheo** [comment]
I'm also having this error. First time posting in github issues... so i'll try my best to get you all the info:

Python : 3.9
Python: 3.10
Python: 3.11
I've tried all 3

* MacOS version :Montery 12.6,1
* XCode Version : 14
* Cython==0.29.28

**Describe the bug**
Throws and error on compiling.  I have tried everything listed above on all 3 python versions. I've deleted and restarted multiple times. 

**Expected behavior**
git clone https://github.com/kivy/kivy-ios.git
cd kivy-ios/
python3 -m venv venv
. venv/bin/activate
pip install -e .
toolchain build python3 kivy pillow
toolchain pip install kivymd mongoengine watchdog dnspython pandas
toolchain pip install Cython==0.29.28
toolchain create project /directory
open project

**Logs**
```
2022-11-13 05:33:25.488372-0500 CWA[68815:4570094] Available orientation: KIVY_ORIENTATION=Portrait PortraitUpsideDown
2022-11-13 05:33:25.488792-0500 CWA[68815:4570094] Initializing python
2022-11-13 05:33:25.903754-0500 CWA[68815:4570094] Running main.py: /Users/tk/Library/Developer/CoreSimulator/Devices/702F62D4-9CC7-452C-BD05-E7B658E5447F/data/Containers/Bundle/Application/AE07554A-694B-478F-8C3E-C13201DD7D02/CWA.app/YourApp/main.pyc
[INFO   ] [Logger      ] Record log in /Users/tk/Library/Developer/CoreSimulator/Devices/702F62D4-9CC7-452C-BD05-E7B658E5447F/data/Containers/Data/Application/FF7A558D-3074-4717-BB5D-B091B40628FC/Documents/.kivy/logs/kivy_22-11-13_5.txt
[INFO   ] [Kivy        ] v2.2.0.dev0
[INFO   ] [Kivy        ] Installed at "/Users/tk/Library/Developer/CoreSimulator/Devices/702F62D4-9CC7-452C-BD05-E7B658E5447F/data/Containers/Bundle/Application/AE07554A-694B-478F-8C3E-C13201DD7D02/CWA.app/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.9.9 (main, Nov 13 2022, 04:47:36) 
[Clang 14.0.0 (clang-1400.0.29.202)]
[INFO   ] [Python      ] Interpreter at "/Users/tk/Library/Developer/CoreSimulator/Devices/702F62D4-9CC7-452C-BD05-E7B658E5447F/data/Containers/Bundle/Application/AE07554A-694B-478F-8C3E-C13201DD7D02/CWA.app/CWA"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[ERROR  ] [Clock       ] Unable to import kivy._clock. Have you perhaps forgotten to compile kivy? Kivy contains Cython code which needs to be compiled. A missing kivy._clock often indicates the Cython code has not been compiled. Please follow the installation instructions and make sure to compile Kivy
 Traceback (most recent call last):
   File "<string>", line 44, in load_module
   File "/Users/tk/kivy-ios/dist/root/python3/lib/python3.9/imp.py", line 342, in load_dynamic
   File "<frozen importlib._bootstrap>", line 711, in _load
   File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
   File "<frozen importlib._bootstrap>", line 565, in module_from_spec
   File "<frozen importlib._bootstrap_external>", line 1173, in create_module
   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
 ImportError: dynamic module does not define module export function (PyInit_kivy__clock)
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/Users/tk/kivy-ios/cwa-ios/YourApp/main.py", line 25, in <module>
   File "/Users/tk/Library/Developer/CoreSimulator/Devices/702F62D4-9CC7-452C-BD05-E7B658E5447F/data/Containers/Bundle/Application/AE07554A-694B-478F-8C3E-C13201DD7D02/CWA.app/lib/python3.9/site-packages/kivy/core/window/__init__.py", line 18, in <module>
     from kivy.clock import Clock
   File "/Users/tk/Library/Developer/CoreSimulator/Devices/702F62D4-9CC7-452C-BD05-E7B658E5447F/data/Containers/Bundle/Application/AE07554A-694B-478F-8C3E-C13201DD7D02/CWA.app/lib/python3.9/site-packages/kivy/clock.py", line 466, in <module>
     from kivy._clock import CyClockBase, ClockEvent, FreeClockEvent, \
   File "<string>", line 48, in load_module
   File "/Users/tk/kivy-ios/dist/root/python3/lib/python3.9/imp.py", line 342, in load_dynamic
 ImportError: dynamic module does not define module export function (PyInit__clock)
2022-11-13 05:33:26.950785-0500 CWA[68815:4570094] Application quit abnormally!
2022-11-13 05:33:26.971313-0500 CWA[68815:4570094] Leaving
```

**Additional context**.
I have to set the: Target -> Build Settings -> enable testability -> No

otherwise i get this error:
```
 /Users/tk/kivy-ios/dist/lib/libfreetype.a(ftcache.o)
    /Users/tk/kivy-ios/dist/lib/libsdl2_ttf.a(ftcache.o)
ld: 407 duplicate symbols for architecture x86_64
```
I hope that helps! Please help me asap as well.

**Comment by lukebelz** [comment]
Just to get a few details out of the way, I'm running the latest kivy-ios pulled from github.

Name: kivy-ios
Version: 2023.5.21

I'm having a lot of issues getting Pillow to work. Unlike most, I'm not using kivyMD. I'm using pillow to draw text onto an image. When I compile it with kivy on my m1 macbook pro, everything works great using:
- Python 3.11.4
- Pillow 10.0.0.

With kivy-ios, this is what I've tried:

toolchain build python3 kivy 
toolchain build pillow

That gives the following error:

407 duplicate symbols for architecture arm64
Linker command failed with exit code 1 (use -v to see invocation)


Now if If I "pip install pillow" instead of using "toolchain build pillow", which will give me pillow 10.0.0 instead of pillow the 8.2 given in toolchain:

File "/Users/username/Desktop/dist/root/python3/lib/python3.10/imp.py", line 343, in load_dynamic
 ImportError: dynamic module does not define module export function (PyInit__imaging)


Any suggestions? Only other library I need is pymysql which pip installs just fine. It's just Pillow that's creating issues.

**Comment by tomasemilio** [comment]
I think I might have found something:
```bash
toolchain pip uninstall pillow
toolchain clean pillow
toolchain build pillow
```
This downgraded pillow to the working version.

**Comment by abdul-yusuf** [comment]
> I have fixed my error
> 
> Thank you

How did you fixed it please

**Comment by Julian-O** [comment]
This is a support issue with three fixes proposed above. 

Closing as there is no work to be done by Kivy developers.
